### ISSUE TITLE
JupyterLab statusbar is not shown

### ISSUE THREAD

**Issue by ekungurov** [atisor73/jupyterlab-themes#1]
On recent versions of JupyterLab (at least 3.4.x) statusbar dissapear when using the themes.

**Comment by atisor73** [comment]
I can look into this, I only tested the themes on 3.2. 
Out of curiosity, do all the themes make the status bar disappear for you?

**Comment by ekungurov** [comment]
All themes in the repo, yes. I think a fix might be something like:
https://github.com/mohirio/jupyterlab-horizon-theme/commit/f3b370069e3e050717ac2694f88d3ca8be8cbc98

**Comment by automataIA** [comment]
I have the same issues. But this problem came from the original mexico-16. 
I try this (https://github.com/mohirio/jupyterlab-horizon-theme/commit/f3b370069e3e050717ac2694f88d3ca8be8cbc98) but don't work.
**EDIT: _NOW Work with this piece of code in the CSS file._** 
You have to rebuild jupyterlab, after changed, with:
`jupyter lab build`

**Comment by atisor73** [comment]
The newest versions have included the statusbar-height variable.
